# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "npm-11.10.0" = {
      name = "npm";
      packageName = "npm";
      version = "11.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm/-/npm-11.10.0.tgz";
        sha512 = "i8hE43iSIAMFuYVi8TxsEISdELM4fIza600aLjJ0ankGPLqd0oTPKMJqAcO/QWm307MbSlWGzJcNZ0lGMQgHPA==";
      };
    };
    "npx-10.2.2" = {
      name = "npx";
      packageName = "npx";
      version = "10.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npx/-/npx-10.2.2.tgz";
        sha512 = "eImmySusyeWphzs5iNh791XbZnZG0FSNvM4KSah34pdQQIDsdTDhIwg1sjN3AIVcjGLpbQ/YcfqHPshKZQK1fA==";
      };
    };
    "pnpm-10.29.3" = {
      name = "pnpm";
      packageName = "pnpm";
      version = "10.29.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pnpm/-/pnpm-10.29.3.tgz";
        sha512 = "SY4ftMylqgbB3PJhHm+vxQly/+cYmZjECekN50VmREKY/+Q+bNKs3Hdboap8xeCSqLcFTIEbqMV3D4RpPTPS3A==";
      };
    };
  };
  args = {
    name = "nazozo-node-tools";
    packageName = "nazozo-node-tools";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."npm-11.10.0"
      sources."npx-10.2.2"
      sources."pnpm-10.29.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
