name: "Reusable: Nix CI job"

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      timeout-minutes:
        required: false
        type: number
        default: 10
      run-command:
        required: true
        type: string

jobs:
  run:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Run command
        run: ${{ inputs.run-command }}
