name: "CI: Lint (actions)"
on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"
  push:
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    uses: ./.github/workflows/_nix-ci.yml
    with:
      run-command: nix shell nixpkgs#actionlint --command actionlint
      timeout-minutes: 10
