# .github/workflows/flake-check.yml
name: Nix Flake Check
on:
  push:
    branches: [main]
    paths:
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/flake-check.yml"
      - ".github/workflows/_nix-ci.yml"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/_nix-ci.yml
    with:
      run-command: nix flake check --no-build
      timeout-minutes: 10
