name: Nix Flake Check
on:
  push:
    branches: [main]
    paths:
      - "flake.nix"
      - "flake.lock"
      - "nix/**"
      - ".github/workflows/flake-check.yml"
      - ".github/workflows/_nix-ci.yml"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: flake-check (${{ matrix.os }})
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    uses: ./.github/workflows/_nix-ci.yml
    with:
      runs-on: ${{ matrix.os }}
      run-command: nix flake check
      timeout-minutes: 20

  fmt-check:
    name: treefmt-ci (${{ matrix.os }})
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    uses: ./.github/workflows/_nix-ci.yml
    with:
      runs-on: ${{ matrix.os }}
      run-command: nix fmt -- --ci
      timeout-minutes: 10
