name: "CI: Lint (Lua)"
on:
  pull_request: {}
  push:
    paths:
      - "nvim/**/*.lua"
      - ".github/workflows/nvim-lint.yml"

jobs:
  lua-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v12

      - name: StyLua auto-fix
        run: |
          nix shell nixpkgs#stylua --command stylua nvim/

      - name: Create PR if StyLua made changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "style: auto-fix StyLua formatting"
          title: "style: auto-fix StyLua formatting"
          body: "StyLua によるフォーマット自動修正"
          branch: "fix/stylua-auto-format"

      - name: luacheck
        run: |
          luacheck nvim/ --globals vim; code=$?; [ $code -lt 2 ]
